In [36]:
import numpy as np
import pandas as pd

imported the libraries

In [37]:
from  sklearn.datasets import load_iris
iris_dataset= load_iris()

dataset imported

In [38]:
print("Keys of iris_dataset:\n{}".format(iris_dataset.keys()))


Keys of iris_dataset:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


printed the keys of dataset

In [39]:
print(iris_dataset['DESCR'][:200]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


printing DESCR dataset characteristics

In [40]:
print("Target names:{}".format(iris_dataset['target_names']))

Target names:['setosa' 'versicolor' 'virginica']


names of flower are printed

In [41]:
print("feature names:{}".format(iris_dataset['feature_names']))

feature names:['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


features are printed

In [42]:
print("Type of data:{}".format(type(iris_dataset['data'])))

Type of data:<class 'numpy.ndarray'>


printing the type od the dataset data

In [43]:
print("shape of data:{}".format(iris_dataset['data'].shape))

shape of data:(150, 4)


printing the shape of dataset data

In [44]:
print("first five columns:{}".format(iris_dataset['data'][:5]))

first five columns:[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


printing first five arrays

In [45]:
print("type OF TArget:{}".format(type(iris_dataset['target'])))

type OF TArget:<class 'numpy.ndarray'>


shape of target

In [46]:
print("shape OF TArget:{}".format((iris_dataset['target'].shape)))

shape OF TArget:(150,)


shape of target is printed

In [47]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


printed the target ie. the type of flowers

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'],random_state =0 )

importing the teain_test_split for training and testing our model

In [49]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1) 

In [ ]:
importing k neighbour classifier and allocating k=1 n_neighbours denotes the k

In [54]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

fitting the data 

In [50]:
X_new = np.array([[5,2.7,1,0.3]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


creating a array for predicting its neighbour

In [58]:
prediction = knn.predict(X_new)

print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
    iris_dataset['target_names'][prediction])
)

Prediction: [0]
Predicted target name: ['setosa']


In [56]:
y_pred = knn.predict(X_test)
print("Test set PRediction: \n {}".format(y_pred))

Test set PRediction: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [59]:
print("Test set score : {}".format(np.mean(y_pred==y_test)))

Test set score : 0.9736842105263158


predicting the accuraccy of the model
Done....